### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by jessicakan789**
Test written for all API stuff. SQL db is not working properly yet so will be tested at a later date. Please keep init.py files in the folders. I will update the readthedocs and other docs. Thanks

### CODE REVIEW

**Comment by jessicakan789** [comment]
WARNING: code in PanelSearch folder now includes "PanelSearch.<file>" otherwise pytest does not work. However, "python main.py" gives ModuleNotFoundError on command line.

**Comment by jessicakan789** [comment]
> WARNING: code in PanelSearch folder now includes "PanelSearch." otherwise pytest does not work. However, "python main.py" gives ModuleNotFoundError on command line.

FIXED by modifying __init__.py

**Comment by TomLivesey-UoM** [comment]
I have manually resolved the merge conflicts with the dev branch - most were only small issues of commented out lines having been deleted BUT **please delete pycache files which aren't 100% necessary before requesting a merge as this can cause complex merge conflicts if in both branches.**

**Review by TomLivesey-UoM — CHANGES_REQUESTED** [review]
- Functions names have been changed to become more PEP8 compliant.
- Error handling added to API request and parsing functions.
- Testing scripts created for each of the API request, parsing, and main.py functions.

I have tried to run the testing scripts but am getting the following error:
"from PanelSearch.<script name> import *

ModuleNotFoundError: No module named 'PanelSearch'"

@jessicakan789 could you please review this?

**Comment by TomLivesey-UoM** [comment]
I have resolved the issues and will now merge

**Pull request merged**
